# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0jc0P3n1FtyKyHeUrHkKMNDoRx7kswy
"""

import pandas as pd

df = pd.read_csv("/content/cleaned_traffic_data_steps_2000_to_3000.csv")

df.head(5)

df = df.drop(columns=["timestep"])

df.head(5)

from os import terminal_size
def get_advice_label(row, balance_threshold=5):
  """
  label_dict = {
    0: "balance-keep",
    1: "balance-switch",
    2: "balance-extend",
    3: "balance-extend_both",
    4: "imbalance-keep",
    5: "imbalance-switch",
    6: "imbalance-extend"
  }
  """

  if abs(row["edge1_waiting_vehicle_count"] - row["edge2_waiting_vehicle_count"]) <= balance_threshold:
    balance = True
  else:
    balance = False


  edge1_congestion = (row["edge1_congestion"] == "Congested")
  edge2_congestion = (row["edge2_congestion"] == "Congested")

  edge1_green = (str(row["edge1_light_state"]).lower() == "g")
  edge2_green = (str(row["edge2_light_state"]).lower() == "g")

  if balance:
    if edge1_congestion and not edge2_congestion:
      if edge1_green:
        return 2
      else:
        return 1
    elif edge2_congestion and not edge1_congestion:
      if edge2_green:
        return 2
      else:
        return 1
    elif edge1_congestion and edge2_congestion:
      return 3
    else:
      return 0

  else:
    if row["edge1_waiting_vehicle_count"] > row["edge2_waiting_vehicle_count"]:
      if edge1_congestion:
        if edge1_green:
          return 6
        else:
          return 5
      else:
        return 4
    else:
      if edge2_congestion:
        if edge2_green:
          return 6
        else:
          return 5
      else:
        return 4

df["label"] = df.apply(get_advice_label, axis=1)

df

df.to_csv("data_with_label.csv", index=False)