# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ffu0rKCPvVRF15VsLutQ8toNEj7XsvfQ
"""

from fastapi import FastAPI
from pydantic import BaseModel, Field
import joblib
import pandas as pd
from typing import List

edge_to_light = {
    ('132200274', 'edge1'): {'from': '-238343434#1_0', 'to': '-1316222932_0'},
    ('132200274', 'edge2'): {'from': '23995336#1_0', 'to': '1316218907_0'},
    ('47217361', 'edge1'): {'from': '51444161_0', 'to': '1314507318_0'},
    ('47217361', 'edge2'): {'from': '937860545_0', 'to': '-115099072#1_0'},
    ('181747232', 'edge1'): {'from': '51425540_0', 'to': '496165839#0_0'},
    ('181747232', 'edge2'): {'from': '25094836#0_0', 'to': '496165839#0_0'},
    ('2455689105', 'edge1'): {'from': '978240443_0', 'to': '978240453_0'},
    ('2455689105', 'edge2'): {'from': '237682631#0_0', 'to': '978240453_0'},
    ('43296523', 'edge1'): {'from': '-405573966#0_0', 'to': '-405573970_0'},
    ('43296523', 'edge2'): {'from': '1316218908_0', 'to': '-1316218909_0'},

    ('cluster_1420096799_47154676', 'edge1'): {'from': '1137430188#1_0', 'to': '1137430198_0'},
    ('cluster_1420096799_47154676', 'edge2'): {'from': '-22941953_0', 'to': '-1318757313_0'},
    ('cluster_181310323_5380872437', 'edge1'): {'from': '1314507334#1_0', 'to': '405573977#0_0'},
    ('cluster_181310323_5380872437', 'edge2'): {'from': '17505124#14_0', 'to': '-558009505#3_0'},
    ('cluster_2455590523_389713_47212064', 'edge1'): {'from': '-23017365#1_0', 'to': '1323344866#0_0'},
    ('cluster_2455590523_389713_47212064', 'edge2'): {'from': '-1323344866#1_0', 'to': '23017365#0_0'},
    ('cluster_2461783448_38980632_5243070374', 'edge1'): {'from': '-5408682#0_0', 'to': '5745067#0_0'},
    ('cluster_2461783448_38980632_5243070374', 'edge2'): {'from': '238328028#0_0', 'to': '1013488730#0_0'},
    ('cluster_2461880040_2461880142_8131892137', 'edge1'): {'from': '-1230140225_0', 'to': '-41517970_0'},
    ('cluster_2461880040_2461880142_8131892137', 'edge2'): {'from': '238343454#0_0', 'to': '592091326#1_0'},
    ('cluster_2461880136_4910664147_50607912_8131882097', 'edge1'): {'from': '-6117802#2_0', 'to': '-891083015_0'},
    ('cluster_2461880136_4910664147_50607912_8131882097', 'edge2'): {'from': '-313901238#2_0', 'to': '-41517971#1_0'},
    ('cluster_32335123_4338281374', 'edge1'): {'from': '978240454#0_0', 'to': '435936410_0'},
    ('cluster_32335123_4338281374', 'edge2'): {'from': '-435936410_0', 'to': '-978240454#1_0'},
    ('cluster_59665162_8742497506', 'edge1'): {'from': '-1283019234#1_0', 'to': '-944263093_0'},
    ('cluster_59665162_8742497506', 'edge2'): {'from': '-1358634026#3_0', 'to': '-1358634026#1_0'},
    ('cluster_59665162_8742497506', 'edge1'): {'from': '-1283019234#1_0', 'to': '-944263093_0'},
    ('cluster_59665162_8742497506', 'edge2'): {'from': '-1358634026#3_0', 'to': '-1358634026#1_0'},

    ## do not have conflict road
    ('38980650', 'edge1'): {'from': '-143291861_0', 'to': '-542295428#7_0'},
    ('43296523', 'edge1'): {'from': '-405573966#0_0', 'to': '-405573970_0'},
    ('43314904', 'edge1'): {'from': '1316218908_0', 'to': '-1316218909_0'},
    ('47217357', 'edge1'): {'from': '899632449_0', 'to': '5856723_0'},
    ('50877750', 'edge1'): {'from': '-1390498518_0', 'to': '-65582159_0'},
    ('50877815', 'edge1'): {'from': '-6145626#8_0', 'to': '-6145626#4_0'},
    ('cluster_5282839762_5528420376', 'edge1'): {'from': '-1390498518_0', 'to': '143299839_0'},
    ('cluster_669501977_9051819726_947981611', 'edge1'): {'from': '-1099729683#0_0', 'to': '978240442_0'}

}

class SuggestionInput(BaseModel):
  junctionid: str
  edge1_vehicle_count: int
  edge2_vehicle_count: int
  edge1_waiting_vehicle_count: int
  edge2_waiting_vehicle_count: int
  edge1_light_state: int
  edge2_light_state: int
  nextswitchtime: int = Field(..., alias="next_switch_time")

app = FastAPI()
clf = joblib.load("suggestion_model.pkl")

@app.post("/predict_batch")
def predict(inputs: List[SuggestionInput]):
  feature_list = []
  for input in inputs:
      d = input.dict()
      feature_list.append({
          "edge1_vehicle_count": d["edge1_vehicle_count"],
          "edge2_vehicle_count": d["edge2_vehicle_count"],
          "edge1_waiting_vehicle_count": d["edge1_waiting_vehicle_count"],
          "edge2_waiting_vehicle_count": d["edge2_waiting_vehicle_count"],
          "edge1_light_state": d["edge1_light_state"],
          "edge2_light_state": d["edge2_light_state"],
          "nextswitchtime": d["nextswitchtime"],
      })
  X = pd.DataFrame(feature_list)
  y_pred = clf.predict(X)

  suggestions = []
  for i in range(len(inputs)):
    row = feature_list[i]
    suggestion = get_suggestion_details(y_pred[i], row, inputs[i].junctionid)
    suggestions.append(suggestion["suggestions"])
  return {"batch_suggestions": suggestions}

def get_suggestion_details(label, row, junctionid):
  suggestions = []
  if label in [1, 5]: ## change state to green
    if row["edge1_waiting_vehicle_count"] >= row["edge2_waiting_vehicle_count"]:
      target_edge = "edge1"
    else:
      target_edge = "edge2"
    state = 0
    duration = 0 ## if duration=0, then frontend need to get the duration in SUMO and send it to the backend
    signal_info = edge_to_light.get((junctionid, target_edge), {})
    suggestions.append({
        "suggestion_label": int(label),
        "junction": junctionid,
        "edge": target_edge,
        "target_light_from": signal_info.get("from", ""),
        "target_light_to": signal_info.get("to", ""),
        "target_state": state,
        "duration": duration
    })
  elif label in [2, 6]: ## add 20s
    if row["edge1_light_state"] == 0:
      target_edge = "edge1"
    else:
      target_edge = "edge2"
    duration = 20 ## add 20s
    signal_info = edge_to_light.get((junctionid, target_edge), {})
    suggestions.append({
        "suggestion_label": int(label),
        "junction": junctionid,
        "edge": target_edge,
        "target_light_from": signal_info.get("from", ""),
        "target_light_to": signal_info.get("to", ""),
        "target_state": "",
        "duration": duration
    })

  elif label == 3: ## both add 20s, 2 suggestions
     for target_edge in ["edge1", "edge2"]:
      duration = 0
      signal_info = edge_to_light.get((junctionid, target_edge), {})
      suggestions.append({
          "suggestion_label": int(label),
          "junction": junctionid,
          "edge": target_edge,
          "target_light_from": signal_info.get("from", ""),
          "target_light_to": signal_info.get("to", ""),
          "target_state": "",
          "duration": duration ## add 20s
      })

  else: ## keep
    suggestions.append({
        "suggestion_label": int(label),
        "junction": junctionid,
        "edge": "",
        "target_light_from": "",
        "target_light_to": "",  
        "target_state": "",
        "duration": 0
    })
  return {"suggestions": suggestions}

## run the code in terminal
## uvicorn main:api --reload --host 0.0.0.0 --port 8000