# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/128eH6Q1c8U2EybBBXDkB5c0hNOceFMXP
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import joblib

df = pd.read_csv("/content/data_with_label.csv")

df.head(5)

def encode_light_state(state):
  state = str(state).lower()
  if state == "g":
    return 0
  elif state == "r":
    return 1
  elif state == "y":
    return 2
  else:
    return -1

df["edge1_light_state"] = df["edge1_light_state"].apply(encode_light_state)
df["edge2_light_state"] = df["edge2_light_state"].apply(encode_light_state)

df.head(5)

features = [
    "edge1_vehicle_count",
    "edge2_vehicle_count",
    "edge1_waiting_vehicle_count",
    "edge2_waiting_vehicle_count",
    "edge1_light_state",
    "edge2_light_state",
    "nextswitchtime"
]

X = df[features]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
classification_report_str = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Classification Report:\n", classification_report_str)

# save model
joblib.dump(clf, "suggestion_model.pkl")