version: '3.8'

services:


  redis:
    image: redis:latest          # Use the latest Redis image
    container_name: redis        # Name of the container
    ports:
      - "6379:6379"              # Expose Redis on the default port
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:                        # Volume to persist database files
