version: '3.8'

services:
  mysql:
    image: mysql:latest          # Pulls the latest MySQL image
    container_name: urbanflow-mysql     # Name of the container
    ports:
      - "3306:3306"              # Expose MySQL on port 3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Root user password
      MYSQL_DATABASE: urbanflow         # Name of the database to be created
      MYSQL_USER: user                 # Application username
      MYSQL_PASSWORD: password         # Application password
    volumes:
      - db_data:/var/lib/mysql    # Persist MySQL data
    networks:
      - backend

  redis:
    image: redis:latest          # Use the latest Redis image
    container_name: redis        # Name of the container
    ports:
      - "6379:6379"              # Expose Redis on the default port
    networks:
      - backend

  influxdb:
    image: influxdb:latest
    container_name: urbanflow-influxdb
    ports:
      - "9999:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Urb@nFl0w_Dev-Pass!
      - DOCKER_INFLUXDB_INIT_ORG=urbanflow-project
      - DOCKER_INFLUXDB_INIT_BUCKET=traffic_staging_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ThIs_Is_My_S3cr3t_D3v_T0ken_F0r_UrbanFl0w
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
